image:
  repository: rfrcapital/consumer-app  
  tag: "1.0.1"  
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 5672  # Port for internal RabbitMQ communication

env:
  RABBITMQ_HOST: "rabbitmq.default.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
