apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer
  labels:
    app: {{ .Release.Name }}-producer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80  
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-producer
